[package]
name = "rain"
version = "1.0.0"
authors = ["gerald schenk <gschenk@gmx.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.5.6" }
